#!/bin/bash

export PYTHONPATH="/home/arjun/CM/repos/local/cache/e15bfdcfabe545b8/inference/vision/classification_and_detection/python:/home/arjun/CM/repos/local/cache/e15bfdcfabe545b8/inference/tools/submission:/home/arjun/CM/repos/local/cache/d57d3ceb23e74e86/inference/vision/classification_and_detection/python:/home/arjun/CM/repos/local/cache/d57d3ceb23e74e86/inference/tools/submission:${PYTHONPATH}"
export CM_HW_NAME="phoenix_Amd_Am5"
export CM_MLPERF_CLEAN_SUBMISSION_DIR="True"
export CM_MLPERF_DUPLICATE_SCENARIO_RESULTS="yes"
export CM_MLPERF_INFERENCE_3DUNET_PATH="/home/arjun/CM/repos/local/cache/d57d3ceb23e74e86/inference/vision/medical_imaging/3d-unet-kits19"
export CM_MLPERF_INFERENCE_BERT_PATH="/home/arjun/CM/repos/local/cache/d57d3ceb23e74e86/inference/language/bert"
export CM_MLPERF_INFERENCE_CLASSIFICATION_AND_DETECTION_PATH="/home/arjun/CM/repos/local/cache/d57d3ceb23e74e86/inference/vision/classification_and_detection"
export CM_MLPERF_INFERENCE_DLRM_PATH="/home/arjun/CM/repos/local/cache/d57d3ceb23e74e86/inference/recommendation/dlrm"
export CM_MLPERF_INFERENCE_RNNT_PATH="/home/arjun/CM/repos/local/cache/d57d3ceb23e74e86/inference/speech_recognition/rnnt"
export CM_MLPERF_INFERENCE_SOURCE="/home/arjun/CM/repos/local/cache/d57d3ceb23e74e86/inference"
export CM_MLPERF_INFERENCE_VISION_PATH="/home/arjun/CM/repos/local/cache/d57d3ceb23e74e86/inference/vision"
export CM_MLPERF_LAST_RELEASE="v3.0"
export CM_MLPERF_RESULTS_DIR="/home/arjun/find_performance/test_results"
export CM_MLPERF_SHORT_RUN="no"
export CM_MLPERF_SUBMISSION_DIR="/home/arjun/mobilenet_submission_tree1"
export CM_MLPERF_SUBMITTER="cTuning"
export CM_MLPERF_SUT_HW_NOTES_EXTRA="Result taken by NAME"
export CM_PANDAS_VERSION="1.5.3"
export CM_POST_RUN_CMD="/usr/bin/python3 /home/arjun/CM/repos/local/cache/d57d3ceb23e74e86/inference/tools/submission/generate_final_report.py --input summary.csv"
export CM_PYTHONLIB_BOTO3_CACHE_TAGS="version-1.26.74"
export CM_PYTHONLIB_NUMPY_CACHE_TAGS="version-1.24.2"
export CM_PYTHONLIB_OPENCV_PYTHON_CACHE_TAGS="version-4.7.0.68"
export CM_PYTHONLIB_PANDAS_CACHE_TAGS="version-1.5.3"
export CM_PYTHONLIB_REQUESTS_CACHE_TAGS="version-2.25.1"
export CM_PYTHONLIB_TQDM_CACHE_TAGS="version-4.64.1"
export CM_PYTHONLIB_XLSXWRITER_CACHE_TAGS="version-3.0.8"
export CM_PYTHON_BIN="python3"
export CM_PYTHON_BIN_PATH="/usr/bin"
export CM_PYTHON_BIN_WITH_PATH="/usr/bin/python3"
export CM_PYTHON_CACHE_TAGS="version-3.10.6,non-virtual"
export CM_PYTHON_VERSION="3.10.6"
export CM_RUN_CMD="/usr/bin/python3 /home/arjun/CM/repos/local/cache/d57d3ceb23e74e86/inference/tools/submission/submission_checker.py --input "/home/arjun/mobilenet_submission_tree1" --submitter "cTuning" "
export CM_RUN_MLPERF_ACCURACY="on"
export CM_RUN_SUBMISSION_CHECKER="True"
export CM_SUT_DESC_CACHE="yes"
export CM_TMP_CURRENT_PATH="/home/arjun/mobilenet_submission_tree/open/cTuning/measurements/phoenix_Amd_Am5-tflite_cpp-cpu-tflite-vmaster-default_config"
export CM_TMP_CURRENT_SCRIPT_PATH="/home/arjun/CM/repos/octoml@ck/cm-mlops/script/run-mlperf-inference-submission-checker"
export CM_TMP_PIP_VERSION_STRING=""
export CM_XLSXWRITER_VERSION="3.0.8"


. /home/arjun/CM/repos/octoml@ck/cm-mlops/script/run-mlperf-inference-submission-checker/run.sh
